---
#playbook to install base lamp packages, fail2ban, postfix, apticron
#installs:
# php 5.6
# python-software-properties for php 5.6 install
# php5-myslnd
# php5-curl
# apache2
# fail2ban
# apticron
# postfix

- hosts: #add hosts here
  sudo: true  
  tasks:
  - name: add php 5.6 repo
    apt_repository: repo='ppa:ondrej/php5-5.6'
  - name: apt-get update
    apt: update_cache=yes
  - name: install packages
    apt: name={{item}} state=present
    with_items:
    - php5
    - php5-mysqlnd
    - php5-curl
    - python-software-properties
    - apache2
    - fail2ban
    - postfix
    - apticron
  - name: update repo cache 
    apt: update_cache=yes
  - name: update all packages to latest version
    apt: upgrade=dist
